// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: classifications/queries/classifications/query_response.proto

package classifications

import (
	fmt "fmt"
	mappable "github.com/AssetMantle/modules/x/classifications/mappable"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryResponse struct {
	List         []*mappable.Mappable `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	PageResponse *query.PageResponse  `protobuf:"bytes,2,opt,name=page_response,json=pageResponse,proto3" json:"page_response,omitempty"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b8710a8cb206de0, []int{0}
}
func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(m, src)
}
func (m *QueryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryResponse)(nil), "assetmantle.modules.classifications.queries.classifications.QueryResponse")
}

func init() {
	proto.RegisterFile("classifications/queries/classifications/query_response.proto", fileDescriptor_0b8710a8cb206de0)
}

var fileDescriptor_0b8710a8cb206de0 = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xb1, 0x4e, 0xc2, 0x40,
	0x1c, 0xc6, 0xdb, 0x82, 0x0e, 0x45, 0x96, 0xc6, 0x81, 0x30, 0x54, 0xe2, 0x02, 0x71, 0xb8, 0x0b,
	0x98, 0x38, 0x14, 0x13, 0x02, 0x0c, 0x18, 0x63, 0x93, 0xc2, 0x68, 0x9a, 0x98, 0x6b, 0x39, 0x6b,
	0x93, 0xb6, 0x57, 0xb9, 0xc3, 0xc8, 0x1b, 0x38, 0xfa, 0x08, 0xc6, 0xd1, 0xc5, 0xd7, 0x50, 0x27,
	0x46, 0x47, 0x53, 0x36, 0x9f, 0xc2, 0xb4, 0x3d, 0x09, 0x9c, 0x0e, 0x24, 0x6c, 0xff, 0x7e, 0xbd,
	0xef, 0xbb, 0xdf, 0x7d, 0xf9, 0xab, 0xa7, 0x6e, 0x80, 0x28, 0xf5, 0xaf, 0x7d, 0x17, 0x31, 0x9f,
	0x44, 0x14, 0xde, 0x4e, 0xf1, 0xc4, 0xc7, 0x14, 0xfe, 0xa7, 0xcf, 0xae, 0x26, 0x98, 0xc6, 0x24,
	0xa2, 0x18, 0xc4, 0x13, 0xc2, 0x88, 0xd6, 0x46, 0x94, 0x62, 0x16, 0xa2, 0x88, 0x05, 0x18, 0x84,
	0x64, 0x3c, 0x0d, 0x30, 0x05, 0x82, 0x13, 0xf0, 0x44, 0x51, 0xaf, 0xd6, 0xc5, 0x2b, 0x42, 0x14,
	0xc7, 0xc8, 0x09, 0xf0, 0x72, 0xc8, 0x6f, 0xa9, 0x1e, 0xb9, 0x84, 0x86, 0x84, 0x42, 0x07, 0x51,
	0x9c, 0x73, 0xc0, 0xbb, 0xa6, 0x83, 0x19, 0x6a, 0xc2, 0x18, 0x79, 0x7e, 0x94, 0xd9, 0xf9, 0xd9,
	0x7d, 0x8f, 0x78, 0x24, 0x1b, 0x61, 0x3a, 0xe5, 0xea, 0xe1, 0xab, 0xac, 0x96, 0x87, 0xa9, 0x71,
	0xc4, 0xf9, 0xb5, 0x73, 0xb5, 0x18, 0xf8, 0x94, 0x55, 0xe4, 0x5a, 0xa1, 0x51, 0x6a, 0x9d, 0x80,
	0x4d, 0x1e, 0xb2, 0xc4, 0x32, 0xf9, 0x30, 0xca, 0x32, 0xb4, 0x0b, 0xb5, 0x1c, 0x23, 0x0f, 0x2f,
	0xcb, 0xa9, 0x28, 0x35, 0xb9, 0x51, 0x6a, 0xd5, 0x41, 0xce, 0x0d, 0x52, 0xee, 0xac, 0x85, 0x19,
	0xe0, 0xdc, 0xc0, 0x42, 0x1e, 0xfe, 0x65, 0x19, 0xed, 0xc5, 0x2b, 0x5f, 0x46, 0xf1, 0xe1, 0xe9,
	0x40, 0xea, 0xbd, 0x17, 0xde, 0x12, 0x5d, 0x9e, 0x27, 0xba, 0xfc, 0x95, 0xe8, 0xf2, 0xe3, 0x42,
	0x97, 0xe6, 0x0b, 0x5d, 0xfa, 0x5c, 0xe8, 0x92, 0xda, 0x71, 0x49, 0x08, 0xb6, 0x28, 0xbe, 0xa7,
	0xad, 0x55, 0x61, 0xa5, 0x0d, 0x59, 0xf2, 0xe5, 0x99, 0xe7, 0xb3, 0x9b, 0xa9, 0x03, 0x5c, 0x12,
	0xc2, 0x6e, 0x9a, 0x6e, 0x66, 0xe9, 0x90, 0xa7, 0xc3, 0x7b, 0xb8, 0xe1, 0xaa, 0x3c, 0x2b, 0x3b,
	0x5d, 0xb3, 0x3f, 0xec, 0xbf, 0x28, 0xed, 0xee, 0x0a, 0xa5, 0xc9, 0x29, 0xfb, 0x02, 0xe5, 0x90,
	0x53, 0x0a, 0xfa, 0xc7, 0x9a, 0xdb, 0xe6, 0x6e, 0x5b, 0x38, 0x65, 0x73, 0xb7, 0xa8, 0x27, 0xca,
	0x60, 0x0b, 0xb7, 0x3d, 0xb0, 0x7a, 0x26, 0x66, 0x68, 0x8c, 0x18, 0xfa, 0x56, 0x3a, 0x2b, 0x49,
	0x86, 0xc1, 0xa3, 0x0c, 0x43, 0xf0, 0x18, 0x06, 0x0f, 0xfb, 0xf3, 0xc7, 0xd9, 0xcd, 0x96, 0xf0,
	0xf8, 0x27, 0x00, 0x00, 0xff, 0xff, 0x41, 0x76, 0x88, 0xac, 0x6c, 0x03, 0x00, 0x00,
}

func (m *QueryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PageResponse != nil {
		{
			size, err := m.PageResponse.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQueryResponse(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.List) > 0 {
		for iNdEx := len(m.List) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.List[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQueryResponse(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQueryResponse(dAtA []byte, offset int, v uint64) int {
	offset -= sovQueryResponse(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.List) > 0 {
		for _, e := range m.List {
			l = e.Size()
			n += 1 + l + sovQueryResponse(uint64(l))
		}
	}
	if m.PageResponse != nil {
		l = m.PageResponse.Size()
		n += 1 + l + sovQueryResponse(uint64(l))
	}
	return n
}

func sovQueryResponse(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQueryResponse(x uint64) (n int) {
	return sovQueryResponse(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQueryResponse
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field List", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQueryResponse
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQueryResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.List = append(m.List, &mappable.Mappable{})
			if err := m.List[len(m.List)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PageResponse", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQueryResponse
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQueryResponse
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQueryResponse
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PageResponse == nil {
				m.PageResponse = &query.PageResponse{}
			}
			if err := m.PageResponse.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQueryResponse(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQueryResponse
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQueryResponse(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQueryResponse
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQueryResponse
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQueryResponse
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQueryResponse
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQueryResponse
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQueryResponse
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQueryResponse        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQueryResponse          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQueryResponse = fmt.Errorf("proto: unexpected end of group")
)
