- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "documentation"
  color: "0075ca"
  description: "Changes and features related to documentation"
- name: "duplicate"
  color: "cfd8d7"
  description: "This issue or pull request already exists"
- name: "enhancement"
  color: "a22eef"
- name: "wontfix"
  color: "000000"
  description: "This will not be worked on"
- name: "question"
  color: "d876e3"
  description: "Further information is requested"
- name: "build/cicd"
  color: "e4e669"
  description: ""
- name: "test"
  color: "008672"
  description: ""
- name: "proto"
  color: "4ad73a"
  description: "Protobuf"
- name: "proto"
  color: "4ad73a"
  description: "Protobuf"
