// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: persistence_sdk/modules/identities/internal/mappable/identity.proto

package mappable

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	base "github.com/persistenceOne/persistenceSDK/schema/traits/base"
	github_com_persistenceOne_persistenceSDK_schema_types "github.com/persistenceOne/persistenceSDK/schema/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Identity struct {
	ID            github_com_persistenceOne_persistenceSDK_schema_types.ID `protobuf:"bytes,1,opt,name=i_d,json=iD,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.ID" json:"i_d"`
	HasImmutables base.HasImmutables                                       `protobuf:"bytes,2,opt,name=has_immutables,json=hasImmutables,proto3" json:"has_immutables"`
	HasMutables   base.HasMutables                                         `protobuf:"bytes,3,opt,name=has_mutables,json=hasMutables,proto3" json:"has_mutables"`
}

func (m *Identity) Reset()         { *m = Identity{} }
func (m *Identity) String() string { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()    {}
func (*Identity) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c7982e5d5467bfd, []int{0}
}
func (m *Identity) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Identity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Identity.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Identity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identity.Merge(m, src)
}
func (m *Identity) XXX_Size() int {
	return m.Size()
}
func (m *Identity) XXX_DiscardUnknown() {
	xxx_messageInfo_Identity.DiscardUnknown(m)
}

var xxx_messageInfo_Identity proto.InternalMessageInfo

func (m *Identity) GetHasImmutables() base.HasImmutables {
	if m != nil {
		return m.HasImmutables
	}
	return base.HasImmutables{}
}

func (m *Identity) GetHasMutables() base.HasMutables {
	if m != nil {
		return m.HasMutables
	}
	return base.HasMutables{}
}

func init() {
	proto.RegisterType((*Identity)(nil), "persistence_sdk.modules.identities.internal.mappable.Identity")
}

func init() {
	proto.RegisterFile("persistence_sdk/modules/identities/internal/mappable/identity.proto", fileDescriptor_0c7982e5d5467bfd)
}

var fileDescriptor_0c7982e5d5467bfd = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xbf, 0x4e, 0xc3, 0x30,
	0x18, 0xc4, 0xe3, 0x16, 0x21, 0x48, 0x81, 0x21, 0x62, 0xa8, 0x3a, 0xb8, 0x15, 0x53, 0x27, 0x5b,
	0x40, 0x85, 0x18, 0x51, 0xe9, 0x40, 0x85, 0x2a, 0x44, 0x59, 0x10, 0x03, 0x95, 0xd3, 0x58, 0x89,
	0x45, 0x1d, 0x47, 0xb1, 0x3b, 0xf4, 0x2d, 0xd8, 0x78, 0xa5, 0x8e, 0x1d, 0x11, 0x43, 0x85, 0x92,
	0x17, 0x41, 0xce, 0x3f, 0x92, 0x4c, 0xd9, 0x3e, 0xcb, 0xba, 0xdf, 0x77, 0x77, 0xb6, 0x79, 0x1f,
	0xd0, 0x50, 0x32, 0xa9, 0xa8, 0xbf, 0xa4, 0x0b, 0xe9, 0x7c, 0x60, 0x2e, 0x9c, 0xf5, 0x8a, 0x4a,
	0xcc, 0x1c, 0xea, 0x2b, 0xa6, 0x98, 0x1e, 0x7d, 0x45, 0x43, 0x9f, 0xac, 0x30, 0x27, 0x41, 0x40,
	0xec, 0x15, 0xcd, 0x2f, 0x37, 0x28, 0x08, 0x85, 0x12, 0xd6, 0xa8, 0x06, 0x41, 0x19, 0x04, 0xfd,
	0x43, 0x50, 0x0e, 0x41, 0x39, 0xa4, 0x77, 0xee, 0x0a, 0x57, 0x24, 0x00, 0xac, 0xa7, 0x94, 0xd5,
	0xbb, 0xa9, 0x1b, 0x92, 0x4b, 0x8f, 0x72, 0x82, 0x55, 0x48, 0x98, 0x92, 0xd8, 0x26, 0x92, 0x62,
	0x8f, 0xc8, 0x29, 0xe7, 0x6b, 0xa5, 0x31, 0x32, 0xd3, 0x8d, 0x9a, 0xe9, 0x66, 0x15, 0xd5, 0xc5,
	0x57, 0xcb, 0x3c, 0x9a, 0x66, 0x61, 0xac, 0x67, 0xb3, 0xcd, 0x16, 0x4e, 0x17, 0x0c, 0xc0, 0xf0,
	0x78, 0x7c, 0xb7, 0xdd, 0xf7, 0x8d, 0x9f, 0x7d, 0xff, 0xd6, 0x65, 0xca, 0x5b, 0xdb, 0x68, 0x29,
	0x38, 0x2e, 0xad, 0x78, 0xf2, 0x69, 0xf9, 0xf8, 0x32, 0x79, 0x2c, 0x16, 0x6e, 0x02, 0x2a, 0xd1,
	0x74, 0x32, 0x6f, 0xb1, 0x89, 0xf5, 0x6e, 0x9e, 0x79, 0x44, 0x2e, 0x58, 0xe1, 0xb6, 0xdb, 0x1a,
	0x80, 0x61, 0xe7, 0xea, 0x12, 0xd5, 0x2b, 0x4b, 0xd5, 0x28, 0xb5, 0x8b, 0xb4, 0x5d, 0xf4, 0x50,
	0x8e, 0x39, 0x3e, 0xd0, 0x86, 0xe6, 0xa7, 0x95, 0xec, 0xd6, 0xab, 0x79, 0xa2, 0xf9, 0x05, 0xbd,
	0x9d, 0xd0, 0x71, 0x43, 0xfa, 0xac, 0xca, 0xee, 0x94, 0xfa, 0x19, 0xbb, 0xdb, 0x08, 0x82, 0x5d,
	0x04, 0xc1, 0x6f, 0x04, 0xc1, 0x67, 0x0c, 0x8d, 0x5d, 0x0c, 0x8d, 0xef, 0x18, 0x1a, 0x6f, 0xb3,
	0xc6, 0x8d, 0x34, 0xf9, 0x4b, 0xf6, 0x61, 0xf2, 0x12, 0xd7, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x30, 0xf3, 0x4d, 0x2a, 0x8a, 0x02, 0x00, 0x00,
}

func (m *Identity) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Identity) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Identity) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.HasMutables.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintIdentity(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.HasImmutables.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintIdentity(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.ID.Size()
		i -= size
		if _, err := m.ID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintIdentity(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintIdentity(dAtA []byte, offset int, v uint64) int {
	offset -= sovIdentity(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Identity) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ID.Size()
	n += 1 + l + sovIdentity(uint64(l))
	l = m.HasImmutables.Size()
	n += 1 + l + sovIdentity(uint64(l))
	l = m.HasMutables.Size()
	n += 1 + l + sovIdentity(uint64(l))
	return n
}

func sovIdentity(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIdentity(x uint64) (n int) {
	return sovIdentity(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Identity) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIdentity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Identity: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Identity: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIdentity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasImmutables", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIdentity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.HasImmutables.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HasMutables", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIdentity
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIdentity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.HasMutables.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIdentity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIdentity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIdentity(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIdentity
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIdentity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIdentity
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIdentity
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIdentity
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIdentity        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIdentity          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIdentity = fmt.Errorf("proto: unexpected end of group")
)
