// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: persistence_sdk/modules/orders/internal/transactions/revoke/message.proto

package revoke

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_persistenceOne_persistenceSDK_schema_types "github.com/persistenceOne/persistenceSDK/schema/types"
	github_com_persistenceOne_persistenceSDK_schema_types_base "github.com/persistenceOne/persistenceSDK/schema/types/base"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	From             github_com_persistenceOne_persistenceSDK_schema_types_base.AccAddress `protobuf:"bytes,1,opt,name=from,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types/base.AccAddress" json:"from" valid:"required~required field From missing"`
	FromID           github_com_persistenceOne_persistenceSDK_schema_types.ID              `protobuf:"bytes,2,opt,name=from_i_d,json=fromID,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.ID" json:"from_i_d" valid:"required~required field FromID missing"`
	ToID             github_com_persistenceOne_persistenceSDK_schema_types.ID              `protobuf:"bytes,3,opt,name=to_i_d,json=toID,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.ID" json:"to_i_d" valid:"required~required field ToID missing"`
	ClassificationID github_com_persistenceOne_persistenceSDK_schema_types.ID              `protobuf:"bytes,4,opt,name=classification_i_d,json=classificationID,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.ID" json:"classification_i_d" valid:"required~required field ClassificationID missing"`
}

func (m Message) Reset()         { m = Message{} }
func (m Message) String() string { return proto.CompactTextString(m) }
func (Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_7069e63d31f993b9, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Message.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return m.Size()
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Message)(nil), "modules.orders.internal.transactions.revoke.Message")
}

func init() {
	proto.RegisterFile("persistence_sdk/modules/orders/internal/transactions/revoke/message.proto", fileDescriptor_7069e63d31f993b9)
}

var fileDescriptor_7069e63d31f993b9 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0xd3, 0xbf, 0x6f, 0xd4, 0x30,
	0x14, 0x07, 0xf0, 0x18, 0xa2, 0xa3, 0x64, 0x42, 0x11, 0x43, 0xc5, 0x90, 0x44, 0x37, 0x21, 0x81,
	0xec, 0x81, 0xa5, 0xea, 0xd6, 0x12, 0x90, 0x22, 0x84, 0x90, 0xa0, 0x13, 0xcb, 0xc9, 0x67, 0xbf,
	0xa4, 0x56, 0x13, 0x3b, 0xf8, 0xf9, 0x2a, 0x21, 0x01, 0x23, 0x62, 0x60, 0x80, 0xff, 0xa0, 0x33,
	0x7f, 0x49, 0xc7, 0x8e, 0x88, 0x21, 0x42, 0x77, 0x0b, 0x03, 0x53, 0xff, 0x02, 0x74, 0x4e, 0x4f,
	0x04, 0x96, 0x3b, 0xd0, 0x6d, 0xcf, 0xb6, 0xbe, 0xcf, 0x1f, 0xf9, 0x47, 0x54, 0xb4, 0x60, 0x51,
	0xa1, 0x03, 0x2d, 0x60, 0x82, 0xf2, 0x84, 0x35, 0x46, 0xce, 0x6a, 0x40, 0x66, 0xac, 0x04, 0x8b,
	0x4c, 0x69, 0x07, 0x56, 0xf3, 0x9a, 0x39, 0xcb, 0x35, 0x72, 0xe1, 0x94, 0xd1, 0xc8, 0x2c, 0x9c,
	0x9a, 0x13, 0x60, 0x0d, 0x20, 0xf2, 0x0a, 0x68, 0x6b, 0x8d, 0x33, 0xf1, 0xbd, 0xab, 0x28, 0xed,
	0xa3, 0x74, 0x15, 0xa5, 0xc3, 0x28, 0xed, 0xa3, 0x77, 0x6e, 0x57, 0xa6, 0x32, 0x3e, 0xc7, 0x96,
	0x55, 0xdf, 0x62, 0xfc, 0x33, 0x8c, 0x6e, 0x3c, 0xed, 0x9b, 0xc6, 0x9f, 0x49, 0x14, 0x96, 0xd6,
	0x34, 0xbb, 0x24, 0x23, 0x77, 0x6f, 0x1e, 0xbe, 0x3d, 0xef, 0xd2, 0xe0, 0x5b, 0x97, 0x3e, 0xaa,
	0x94, 0x3b, 0x9e, 0x4d, 0xa9, 0x30, 0x0d, 0x1b, 0xd8, 0x9f, 0x69, 0x18, 0x0e, 0x5f, 0xe4, 0x4f,
	0x18, 0x8a, 0x63, 0x68, 0x38, 0x73, 0xaf, 0x5b, 0x40, 0x36, 0xe5, 0x08, 0xf4, 0x40, 0x88, 0x03,
	0x29, 0x2d, 0x20, 0x5e, 0x76, 0xe9, 0xfd, 0x53, 0x5e, 0x2b, 0xb9, 0x3f, 0xb6, 0xf0, 0x6a, 0xa6,
	0x2c, 0xc8, 0x77, 0xab, 0x22, 0x2b, 0x15, 0xd4, 0x32, 0x7b, 0x6c, 0x4d, 0x93, 0x35, 0x0a, 0x51,
	0xe9, 0x6a, 0xfc, 0xdc, 0x53, 0xe2, 0x8f, 0x24, 0xda, 0x59, 0x16, 0x13, 0x35, 0x91, 0xbb, 0xd7,
	0xbc, 0xcb, 0x5e, 0xb9, 0xf6, 0xfe, 0xcb, 0x45, 0x8b, 0xfc, 0xb2, 0x4b, 0xe9, 0x06, 0x94, 0x22,
	0xff, 0x8d, 0x19, 0x95, 0x7e, 0x22, 0x7e, 0x4f, 0xa2, 0x91, 0x33, 0x1e, 0x73, 0xdd, 0x63, 0xda,
	0x2d, 0x60, 0xd6, 0x9d, 0xcb, 0x91, 0x19, 0x52, 0x42, 0x67, 0x8a, 0x3c, 0xfe, 0x42, 0xa2, 0x58,
	0xd4, 0x1c, 0x51, 0x95, 0x4a, 0xf0, 0xe5, 0x45, 0x7b, 0x54, 0xe8, 0x51, 0x6f, 0xb6, 0x80, 0xda,
	0x5b, 0x83, 0x7a, 0xf8, 0xc7, 0xe6, 0x43, 0xe0, 0x2d, 0xf1, 0xd7, 0xd2, 0xfe, 0xce, 0x87, 0xb3,
	0x34, 0xf8, 0x71, 0x96, 0x06, 0x87, 0xfa, 0x7c, 0x9e, 0x90, 0x8b, 0x79, 0x42, 0xbe, 0xcf, 0x13,
	0xf2, 0x69, 0x91, 0x04, 0x17, 0x8b, 0x24, 0xf8, 0xba, 0x48, 0x82, 0x97, 0x47, 0x1b, 0x5b, 0xff,
	0xe1, 0xbf, 0x4c, 0x47, 0xfe, 0x95, 0x3f, 0xf8, 0x15, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x31, 0xb3,
	0x2f, 0x75, 0x03, 0x00, 0x00,
}

func (m *Message) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Message) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.ClassificationID.Size()
		i -= size
		if _, err := m.ClassificationID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMessage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.ToID.Size()
		i -= size
		if _, err := m.ToID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMessage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.FromID.Size()
		i -= size
		if _, err := m.FromID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMessage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.From.Size()
		i -= size
		if _, err := m.From.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMessage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintMessage(dAtA []byte, offset int, v uint64) int {
	offset -= sovMessage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Message) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.From.Size()
	n += 1 + l + sovMessage(uint64(l))
	l = m.FromID.Size()
	n += 1 + l + sovMessage(uint64(l))
	l = m.ToID.Size()
	n += 1 + l + sovMessage(uint64(l))
	l = m.ClassificationID.Size()
	n += 1 + l + sovMessage(uint64(l))
	return n
}

func sovMessage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMessage(x uint64) (n int) {
	return sovMessage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Message) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Message: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Message: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.From.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FromID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ToID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassificationID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ClassificationID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMessage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMessage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMessage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMessage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMessage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMessage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMessage = fmt.Errorf("proto: unexpected end of group")
)
