// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: persistence_sdk/modules/splits/internal/queries/service.proto

package queries

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	ownable "github.com/persistenceOne/persistenceSDK/modules/splits/internal/queries/ownable"
	split "github.com/persistenceOne/persistenceSDK/modules/splits/internal/queries/split"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("persistence_sdk/modules/splits/internal/queries/service.proto", fileDescriptor_de83a82abaa25be6)
}

var fileDescriptor_de83a82abaa25be6 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0x2d, 0x48, 0x2d, 0x2a,
	0xce, 0x2c, 0x2e, 0x49, 0xcd, 0x4b, 0x4e, 0x8d, 0x2f, 0x4e, 0xc9, 0xd6, 0xcf, 0xcd, 0x4f, 0x29,
	0xcd, 0x49, 0x2d, 0xd6, 0x2f, 0x2e, 0xc8, 0xc9, 0x2c, 0x29, 0xd6, 0xcf, 0xcc, 0x2b, 0x49, 0x2d,
	0xca, 0x4b, 0xcc, 0xd1, 0x2f, 0x2c, 0x4d, 0x2d, 0xca, 0x04, 0x89, 0xa7, 0x16, 0x95, 0x65, 0x26,
	0xa7, 0xea, 0x15, 0x14, 0xe5, 0x97, 0xe4, 0x0b, 0xe9, 0xa3, 0x69, 0xd7, 0x83, 0x6a, 0xd7, 0x83,
	0x68, 0xd7, 0x83, 0x69, 0xd7, 0x83, 0x6a, 0x97, 0x72, 0x26, 0xd5, 0xbe, 0xfc, 0xf2, 0xbc, 0xc4,
	0xa4, 0x9c, 0x54, 0x30, 0xbf, 0x12, 0x62, 0xab, 0x94, 0x23, 0xc9, 0x8e, 0x06, 0x89, 0xa3, 0x18,
	0x21, 0x93, 0x9e, 0x9f, 0x9f, 0x9e, 0x93, 0xaa, 0x9f, 0x58, 0x90, 0xa9, 0x9f, 0x98, 0x97, 0x97,
	0x5f, 0x92, 0x58, 0x92, 0x99, 0x9f, 0x57, 0x0c, 0x91, 0x35, 0x6a, 0x67, 0xe6, 0x62, 0x0d, 0x04,
	0xa9, 0x16, 0x3a, 0xc0, 0xc8, 0xc5, 0xee, 0x0f, 0x71, 0x82, 0x90, 0xab, 0x1e, 0x89, 0xbe, 0xd5,
	0x83, 0x3a, 0x5e, 0x0f, 0x6c, 0x56, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x94, 0x1b, 0xa5,
	0xc6, 0x14, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x2a, 0xa9, 0x35, 0x5d, 0x7e, 0x32, 0x99, 0x49, 0x41,
	0x48, 0x0e, 0x39, 0x12, 0x82, 0x5d, 0xbc, 0x61, 0xa1, 0x00, 0xd5, 0x25, 0xb4, 0x8b, 0x91, 0x8b,
	0x35, 0x18, 0x24, 0x24, 0xe4, 0x4c, 0xb2, 0xcd, 0x60, 0x71, 0x54, 0xe7, 0xbb, 0x50, 0x66, 0x08,
	0x69, 0x8e, 0x77, 0x4a, 0x3a, 0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4,
	0x18, 0x27, 0x3c, 0x96, 0x63, 0xb8, 0xf0, 0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x86, 0x28, 0x8f,
	0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0x64, 0x33, 0xfc, 0xf3, 0x52, 0xd1,
	0x8d, 0x24, 0x90, 0x3a, 0x92, 0xd8, 0xc0, 0x91, 0x6e, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x80,
	0xb0, 0xde, 0xb6, 0x0c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Ownable(ctx context.Context, in *ownable.QueryRequest, opts ...grpc.CallOption) (*ownable.QueryResponse, error)
	Split(ctx context.Context, in *split.QueryRequest, opts ...grpc.CallOption) (*split.QueryResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Ownable(ctx context.Context, in *ownable.QueryRequest, opts ...grpc.CallOption) (*ownable.QueryResponse, error) {
	out := new(ownable.QueryResponse)
	err := c.cc.Invoke(ctx, "/persistence_sdk.modules.splits.internal.queries.Query/Ownable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Split(ctx context.Context, in *split.QueryRequest, opts ...grpc.CallOption) (*split.QueryResponse, error) {
	out := new(split.QueryResponse)
	err := c.cc.Invoke(ctx, "/persistence_sdk.modules.splits.internal.queries.Query/Split", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Ownable(context.Context, *ownable.QueryRequest) (*ownable.QueryResponse, error)
	Split(context.Context, *split.QueryRequest) (*split.QueryResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Ownable(ctx context.Context, req *ownable.QueryRequest) (*ownable.QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ownable not implemented")
}
func (*UnimplementedQueryServer) Split(ctx context.Context, req *split.QueryRequest) (*split.QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Split not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Ownable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ownable.QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Ownable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/persistence_sdk.modules.splits.internal.queries.Query/Ownable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Ownable(ctx, req.(*ownable.QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Split_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(split.QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Split(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/persistence_sdk.modules.splits.internal.queries.Query/Split",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Split(ctx, req.(*split.QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "persistence_sdk.modules.splits.internal.queries.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ownable",
			Handler:    _Query_Ownable_Handler,
		},
		{
			MethodName: "Split",
			Handler:    _Query_Split_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "persistence_sdk/modules/splits/internal/queries/service.proto",
}
