// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: persistence_sdk/modules/identities/internal/transactions/provision/message.proto

package provision

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_persistenceOne_persistenceSDK_schema_types "github.com/persistenceOne/persistenceSDK/schema/types"
	github_com_persistenceOne_persistenceSDK_schema_types_base "github.com/persistenceOne/persistenceSDK/schema/types/base"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	From       github_com_persistenceOne_persistenceSDK_schema_types_base.AccAddress `protobuf:"bytes,1,opt,name=from,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types/base.AccAddress" json:"from" valid:"required~required field From missing, matches(^[a-z0-9]*$)~field To is invalid"`
	To         github_com_persistenceOne_persistenceSDK_schema_types_base.AccAddress `protobuf:"bytes,2,opt,name=to,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types/base.AccAddress" json:"to" valid:"required~required field To missing, matches(^[a-z0-9]*$)~field To is invalid"`
	IdentityID github_com_persistenceOne_persistenceSDK_schema_types.ID              `protobuf:"bytes,3,opt,name=identity_i_d,json=identityID,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.ID" json:"identity_i_d" valid:"required~required IdentityID missing"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_0604abea0b2258dd, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Message.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return m.Size()
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Message)(nil), "modules.identities.internal.transactions.provision.Message")
}

func init() {
	proto.RegisterFile("persistence_sdk/modules/identities/internal/transactions/provision/message.proto", fileDescriptor_0604abea0b2258dd)
}

var fileDescriptor_0604abea0b2258dd = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x3f, 0x6f, 0x13, 0x31,
	0x18, 0xc6, 0xcf, 0xa1, 0xe2, 0xcf, 0x89, 0x29, 0x62, 0x88, 0x18, 0xee, 0x4e, 0x11, 0x43, 0x41,
	0xad, 0x8d, 0x60, 0x81, 0x6e, 0xad, 0x02, 0x52, 0x84, 0x10, 0xa8, 0x44, 0x0c, 0x54, 0x10, 0x39,
	0xe7, 0xb7, 0x97, 0x57, 0x9c, 0xed, 0xc3, 0xaf, 0xaf, 0x52, 0x19, 0x3a, 0x33, 0x22, 0x3e, 0x41,
	0x16, 0xc4, 0x37, 0x60, 0xe2, 0x03, 0x74, 0xec, 0x88, 0x18, 0x4e, 0x28, 0x59, 0x98, 0xfb, 0x09,
	0x50, 0x2f, 0x97, 0x92, 0x05, 0x01, 0x11, 0xdb, 0x63, 0xcb, 0xfe, 0xf9, 0xf7, 0xc8, 0x6f, 0xf8,
	0xb4, 0x00, 0x47, 0x48, 0x1e, 0x4c, 0x0a, 0x43, 0x52, 0xaf, 0x85, 0xb6, 0xaa, 0xcc, 0x81, 0x04,
	0x2a, 0x30, 0x1e, 0x3d, 0x9e, 0x45, 0xe3, 0xc1, 0x19, 0x99, 0x0b, 0xef, 0xa4, 0x21, 0x99, 0x7a,
	0xb4, 0x86, 0x44, 0xe1, 0xec, 0x01, 0x12, 0x5a, 0x23, 0x34, 0x10, 0xc9, 0x0c, 0x78, 0xe1, 0xac,
	0xb7, 0xed, 0x3b, 0x0d, 0x81, 0xff, 0x22, 0xf0, 0x05, 0x81, 0x2f, 0x13, 0xf8, 0x39, 0xe1, 0xfa,
	0xb5, 0xcc, 0x66, 0xb6, 0xbe, 0x2e, 0xce, 0xd2, 0x9c, 0xd4, 0x9d, 0xac, 0x85, 0x97, 0x1e, 0xcf,
	0xd9, 0xed, 0x2f, 0x2c, 0x5c, 0xdb, 0x77, 0x56, 0x77, 0x58, 0xc2, 0xd6, 0xaf, 0xec, 0x7c, 0x62,
	0xc7, 0x55, 0x1c, 0x7c, 0xab, 0xe2, 0x07, 0x19, 0xfa, 0x71, 0x39, 0xe2, 0xa9, 0xd5, 0x62, 0xa9,
	0xca, 0x13, 0x03, 0xcb, 0xcb, 0x67, 0xbd, 0x47, 0x82, 0xd2, 0x31, 0x68, 0x29, 0xfc, 0x61, 0x01,
	0x24, 0x46, 0x92, 0x80, 0x6f, 0xa7, 0xe9, 0xb6, 0x52, 0x0e, 0x88, 0x4e, 0xab, 0xf8, 0xf9, 0x81,
	0xcc, 0x51, 0x6d, 0x75, 0x1d, 0xbc, 0x29, 0xd1, 0x81, 0x3a, 0x5a, 0x84, 0x64, 0x1f, 0x21, 0x57,
	0xc9, 0x43, 0x67, 0x75, 0xa2, 0x91, 0x08, 0x4d, 0xb6, 0x91, 0x68, 0xe9, 0xd3, 0x31, 0xd0, 0xfa,
	0xab, 0x3d, 0xb9, 0xf9, 0xf6, 0xf6, 0xe6, 0xfd, 0x97, 0xb7, 0x6e, 0xdc, 0x3c, 0x9a, 0x1f, 0x1c,
	0xd8, 0x04, 0x29, 0x41, 0x53, 0xf3, 0xba, 0xbb, 0xb5, 0x75, 0xfb, 0x33, 0x0b, 0x5b, 0xde, 0x76,
	0x5a, 0xb5, 0xfc, 0xc7, 0xff, 0x2e, 0x3f, 0xf8, 0x83, 0xfc, 0xc0, 0xae, 0xa2, 0xde, 0xf2, 0xb6,
	0xfd, 0x81, 0x85, 0x57, 0x9b, 0x8f, 0x3c, 0x1c, 0xe2, 0x50, 0x75, 0x2e, 0xd4, 0x15, 0x8a, 0xa6,
	0xc1, 0xbd, 0x95, 0x1a, 0xf0, 0x7e, 0xef, 0xb4, 0x8a, 0x37, 0x7e, 0x2b, 0xdd, 0x6f, 0x1e, 0xec,
	0xf7, 0x16, 0xda, 0xdd, 0xdd, 0x10, 0xcf, 0x37, 0xb7, 0x2e, 0xbf, 0x9b, 0xc4, 0xc1, 0x8f, 0x49,
	0x1c, 0xec, 0x94, 0xc7, 0xd3, 0x88, 0x9d, 0x4c, 0x23, 0xf6, 0x7d, 0x1a, 0xb1, 0xf7, 0xb3, 0x28,
	0x38, 0x99, 0x45, 0xc1, 0xd7, 0x59, 0x14, 0xbc, 0xd8, 0xfb, 0x6b, 0xb3, 0x7f, 0x9f, 0xf8, 0xd1,
	0xc5, 0x7a, 0x40, 0xef, 0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x2f, 0x64, 0x5a, 0x3e, 0x03,
	0x00, 0x00,
}

func (m *Message) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Message) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.IdentityID.Size()
		i -= size
		if _, err := m.IdentityID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMessage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.To.Size()
		i -= size
		if _, err := m.To.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMessage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.From.Size()
		i -= size
		if _, err := m.From.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMessage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintMessage(dAtA []byte, offset int, v uint64) int {
	offset -= sovMessage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Message) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.From.Size()
	n += 1 + l + sovMessage(uint64(l))
	l = m.To.Size()
	n += 1 + l + sovMessage(uint64(l))
	l = m.IdentityID.Size()
	n += 1 + l + sovMessage(uint64(l))
	return n
}

func sovMessage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMessage(x uint64) (n int) {
	return sovMessage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Message) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Message: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Message: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.From.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field To", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.To.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IdentityID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.IdentityID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMessage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMessage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMessage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMessage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMessage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMessage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMessage = fmt.Errorf("proto: unexpected end of group")
)
