// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: x/splits/internal/transactions/send/transaction_response.proto

package send

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	proto "github.com/gogo/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TransactionResponse struct {
}

func (m *TransactionResponse) Reset()         { *m = TransactionResponse{} }
func (m *TransactionResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionResponse) ProtoMessage()    {}
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3353f72bcf139571, []int{0}
}
func (m *TransactionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TransactionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TransactionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TransactionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionResponse.Merge(m, src)
}
func (m *TransactionResponse) XXX_Size() int {
	return m.Size()
}
func (m *TransactionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TransactionResponse)(nil), "assetmantle.modules.splits.transactions.send.TransactionResponse")
}

func init() {
	proto.RegisterFile("x/splits/internal/transactions/send/transaction_response.proto", fileDescriptor_3353f72bcf139571)
}

var fileDescriptor_3353f72bcf139571 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xb1, 0x4a, 0xf5, 0x30,
	0x18, 0x86, 0xdb, 0xc0, 0xff, 0x0f, 0x1d, 0x15, 0xc1, 0x29, 0x83, 0xf3, 0x21, 0x39, 0xe0, 0x22,
	0x19, 0x84, 0x76, 0x71, 0x2a, 0x14, 0xdb, 0x49, 0x02, 0x92, 0xd3, 0x06, 0x2d, 0xb4, 0x49, 0xe9,
	0xf7, 0x1d, 0xf0, 0x32, 0xbc, 0x06, 0x47, 0xaf, 0x44, 0x9c, 0xce, 0xe8, 0x28, 0xed, 0xe6, 0x45,
	0x88, 0xe4, 0x34, 0x60, 0x04, 0x07, 0xcf, 0xfa, 0xf1, 0xbc, 0xcf, 0xfb, 0x92, 0x24, 0x97, 0x0f,
	0x1c, 0x86, 0xae, 0x45, 0xe0, 0xad, 0x41, 0x3d, 0x1a, 0xd5, 0x71, 0x1c, 0x95, 0x01, 0x55, 0x63,
	0x6b, 0x0d, 0x70, 0xd0, 0xa6, 0x09, 0x2f, 0xb7, 0xa3, 0x86, 0xc1, 0x1a, 0xd0, 0x6c, 0x18, 0x2d,
	0xda, 0xa3, 0x95, 0x02, 0xd0, 0xd8, 0x2b, 0x83, 0x9d, 0x66, 0xbd, 0x6d, 0xb6, 0x9d, 0x06, 0xb6,
	0x18, 0x59, 0x28, 0x62, 0x4e, 0x74, 0x76, 0x92, 0x1c, 0x57, 0xdf, 0xc7, 0x6b, 0xaf, 0xca, 0x3e,
	0xc9, 0xcb, 0x44, 0xe3, 0xdd, 0x44, 0xe3, 0xf7, 0x89, 0xc6, 0x8f, 0x33, 0x8d, 0x76, 0x33, 0x8d,
	0xde, 0x66, 0x1a, 0x25, 0xeb, 0xda, 0xf6, 0xec, 0x90, 0x8e, 0xec, 0xf4, 0x97, 0x86, 0xc2, 0x6d,
	0x2d, 0xe2, 0x9b, 0xec, 0xae, 0xc5, 0xfb, 0xed, 0x86, 0xd5, 0xb6, 0xe7, 0xa9, 0x93, 0xe6, 0x7b,
	0x29, 0xf7, 0x52, 0xfe, 0x87, 0xc7, 0x78, 0x22, 0xff, 0xd2, 0xbc, 0xac, 0xca, 0x67, 0xb2, 0x4a,
	0x83, 0x59, 0xb9, 0x9f, 0x55, 0x2e, 0xb3, 0xaa, 0x70, 0x56, 0xa9, 0x4d, 0xf3, 0xfa, 0x03, 0x97,
	0x1e, 0x97, 0x0b, 0x2e, 0x43, 0x5c, 0x3a, 0x7c, 0x22, 0x17, 0x87, 0xe0, 0xf2, 0xaa, 0xc8, 0x72,
	0x8d, 0xaa, 0x51, 0xa8, 0x3e, 0xc8, 0x3a, 0x88, 0x0a, 0xe1, 0xb3, 0x42, 0x2c, 0x61, 0x21, 0xc2,
	0xb4, 0x10, 0x2e, 0xbe, 0xf9, 0xbf, 0xff, 0xcc, 0xf3, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf0,
	0x8c, 0x5c, 0x8a, 0x0e, 0x02, 0x00, 0x00,
}

func (m *TransactionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TransactionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TransactionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTransactionResponse(dAtA []byte, offset int, v uint64) int {
	offset -= sovTransactionResponse(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TransactionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTransactionResponse(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTransactionResponse(x uint64) (n int) {
	return sovTransactionResponse(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TransactionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTransactionResponse
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TransactionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TransactionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTransactionResponse(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTransactionResponse
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTransactionResponse(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTransactionResponse
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTransactionResponse
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTransactionResponse
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTransactionResponse
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTransactionResponse
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTransactionResponse
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTransactionResponse        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTransactionResponse          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTransactionResponse = fmt.Errorf("proto: unexpected end of group")
)
