// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: identities/key/key.proto

package key

import (
	fmt "fmt"
	base "github.com/AssetMantle/schema/go/ids/base"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Key struct {
	IdentityID *base.IdentityID `protobuf:"bytes,1,opt,name=identity_i_d,json=identityID,proto3" json:"identity_i_d,omitempty"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_03f25e9817011f76, []int{0}
}
func (m *Key) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Key.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return m.Size()
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetIdentityID() *base.IdentityID {
	if m != nil {
		return m.IdentityID
	}
	return nil
}

func init() {
	proto.RegisterType((*Key)(nil), "assetmantle.modules.identities.key.Key")
}

func init() { proto.RegisterFile("identities/key/key.proto", fileDescriptor_03f25e9817011f76) }

var fileDescriptor_03f25e9817011f76 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x3f, 0x4b, 0xc4, 0x30,
	0x18, 0xc6, 0x9b, 0x2a, 0x22, 0xd5, 0xe9, 0xa6, 0xe3, 0x86, 0x20, 0x05, 0xff, 0x4c, 0x09, 0xe8,
	0x96, 0xad, 0x45, 0x90, 0x12, 0x0a, 0xc5, 0x51, 0x0a, 0x47, 0xda, 0xbc, 0x78, 0xe1, 0xae, 0x57,
	0x31, 0x39, 0x30, 0xdf, 0xc2, 0xcf, 0xe0, 0x22, 0xf8, 0x49, 0xc4, 0xe9, 0x46, 0x47, 0x69, 0x37,
	0x3f, 0x85, 0xf4, 0x0c, 0xd7, 0xde, 0x74, 0x43, 0x20, 0xf0, 0xfe, 0x7e, 0xef, 0xf3, 0x90, 0x04,
	0x63, 0x25, 0x61, 0x69, 0x94, 0x51, 0xa0, 0xe9, 0x1c, 0x6c, 0x77, 0xc8, 0xd3, 0x73, 0x6d, 0xea,
	0x51, 0x28, 0xb4, 0x06, 0x53, 0x89, 0xa5, 0x59, 0x00, 0xa9, 0x6a, 0xb9, 0x5a, 0x80, 0x26, 0x3d,
	0x4d, 0xe6, 0x60, 0x27, 0x13, 0x25, 0x35, 0x2d, 0x84, 0x06, 0xea, 0x06, 0x76, 0xaa, 0xe4, 0xbf,
	0x1f, 0x66, 0xc1, 0x01, 0x07, 0x3b, 0x4a, 0x82, 0xd3, 0x7e, 0x36, 0x95, 0x63, 0x74, 0x86, 0xae,
	0x4e, 0xae, 0x2f, 0xc9, 0x70, 0xbb, 0x2e, 0x67, 0x50, 0x09, 0xa2, 0xa4, 0x26, 0xdd, 0x32, 0x92,
	0x38, 0x21, 0xb9, 0xbd, 0x0f, 0xd4, 0xf6, 0x1e, 0xbf, 0xfb, 0x9f, 0x0d, 0x46, 0xeb, 0x06, 0xa3,
	0x9f, 0x06, 0xa3, 0xd7, 0x16, 0x7b, 0xeb, 0x16, 0x7b, 0xdf, 0x2d, 0xf6, 0x82, 0x8b, 0xb2, 0xae,
	0xc8, 0xfe, 0xc2, 0xf1, 0x31, 0x07, 0x9b, 0x75, 0xf5, 0x32, 0xf4, 0x40, 0x1f, 0x95, 0x99, 0xad,
	0x0a, 0x52, 0xd6, 0x15, 0x8d, 0x3a, 0x35, 0xdd, 0xa8, 0xd4, 0xa9, 0xf4, 0x85, 0xee, 0xbe, 0xcd,
	0x9b, 0x7f, 0x18, 0xa5, 0x09, 0xff, 0xf0, 0xc3, 0x68, 0x10, 0x94, 0xba, 0xa0, 0xa4, 0x0f, 0xe2,
	0x60, 0xbf, 0x76, 0xa0, 0xdc, 0x41, 0x79, 0x0f, 0xe5, 0x1c, 0x6c, 0xe3, 0x93, 0xfd, 0x50, 0x7e,
	0x97, 0xc5, 0x29, 0x18, 0x21, 0x85, 0x11, 0xbf, 0xfe, 0xf9, 0x40, 0x60, 0xcc, 0x19, 0x8c, 0xf5,
	0x0a, 0x63, 0x1c, 0x6c, 0x71, 0xb4, 0xf9, 0x82, 0x9b, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4d,
	0x70, 0xf9, 0x75, 0xde, 0x01, 0x00, 0x00,
}

func (m *Key) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Key) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Key) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IdentityID != nil {
		{
			size, err := m.IdentityID.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintKey(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintKey(dAtA []byte, offset int, v uint64) int {
	offset -= sovKey(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Key) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IdentityID != nil {
		l = m.IdentityID.Size()
		n += 1 + l + sovKey(uint64(l))
	}
	return n
}

func sovKey(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozKey(x uint64) (n int) {
	return sovKey(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Key) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowKey
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Key: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Key: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IdentityID", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKey
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthKey
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthKey
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.IdentityID == nil {
				m.IdentityID = &base.IdentityID{}
			}
			if err := m.IdentityID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipKey(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthKey
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipKey(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowKey
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowKey
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowKey
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthKey
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupKey
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthKey
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthKey        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowKey          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupKey = fmt.Errorf("proto: unexpected end of group")
)
