// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: persistence_sdk/modules/orders/internal/transactions/modify/message.proto

package modify

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_persistenceOne_persistenceSDK_schema_types "github.com/persistenceOne/persistenceSDK/schema/types"
	github_com_persistenceOne_persistenceSDK_schema_types_base "github.com/persistenceOne/persistenceSDK/schema/types/base"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	From                  github_com_persistenceOne_persistenceSDK_schema_types_base.AccAddress `protobuf:"bytes,1,opt,name=from,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types/base.AccAddress" json:"from" valid:"required~required field From missing"`
	FromID                github_com_persistenceOne_persistenceSDK_schema_types.ID              `protobuf:"bytes,2,opt,name=from_i_d,json=fromID,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.ID" json:"from_i_d" valid:"required~required field FromID missing"`
	OrderID               github_com_persistenceOne_persistenceSDK_schema_types.ID              `protobuf:"bytes,3,opt,name=order_i_d,json=orderID,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.ID" json:"order_i_d" valid:"required~required field OrderID missing"`
	MakerOwnableSplit     github_com_cosmos_cosmos_sdk_types.Dec                                `protobuf:"bytes,4,opt,name=maker_ownable_split,json=makerOwnableSplit,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"maker_ownable_split" valid:"required~required field MakerOwnableSplit missing"`
	TakerOwnableSplit     github_com_cosmos_cosmos_sdk_types.Dec                                `protobuf:"bytes,5,opt,name=taker_ownable_split,json=takerOwnableSplit,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"taker_ownable_split" valid:"required~required field TakerOwnableSplit missing"`
	ExpiresIn             github_com_persistenceOne_persistenceSDK_schema_types.Height          `protobuf:"bytes,6,opt,name=expires_in,json=expiresIn,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.Height" json:"expires_in" valid:"required~required field ExpiresIn missing"`
	MutableMetaProperties github_com_persistenceOne_persistenceSDK_schema_types.MetaProperties  `protobuf:"bytes,7,opt,name=mutable_meta_properties,json=mutableMetaProperties,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.MetaProperties" json:"mutable_meta_properties" valid:"required~required field MutableMetaProperties missing"`
	MutableProperties     github_com_persistenceOne_persistenceSDK_schema_types.Properties      `protobuf:"bytes,8,opt,name=mutable_properties,json=mutableProperties,proto3,customtype=github.com/persistenceOne/persistenceSDK/schema/types.Properties" json:"mutable_properties" valid:"required~required field MutableProperties missing"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_81cb781fe82216d8, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Message.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return m.Size()
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Message)(nil), "persistence_sdk.modules.orders.internal.transactions.modify.Message")
}

func init() {
	proto.RegisterFile("persistence_sdk/modules/orders/internal/transactions/modify/message.proto", fileDescriptor_81cb781fe82216d8)
}

var fileDescriptor_81cb781fe82216d8 = []byte{
	// 579 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0xd4, 0x31, 0x8f, 0xd3, 0x3c,
	0x18, 0x07, 0xf0, 0xf8, 0x7d, 0x8f, 0xbb, 0x36, 0xdb, 0x05, 0x10, 0x15, 0x43, 0x52, 0x75, 0x40,
	0x0c, 0x90, 0x08, 0xb1, 0x70, 0x07, 0x48, 0xdc, 0xa9, 0x87, 0xa8, 0x50, 0x55, 0xc4, 0xdd, 0xc4,
	0x12, 0xa5, 0xc9, 0xd3, 0xd4, 0x6a, 0x6c, 0x07, 0xdb, 0x05, 0x3a, 0xc0, 0x86, 0xc4, 0x00, 0x02,
	0x36, 0x24, 0x96, 0x7e, 0x09, 0xbe, 0x02, 0xba, 0xf1, 0x46, 0xc4, 0x10, 0xa1, 0x76, 0x61, 0xee,
	0x27, 0x40, 0x71, 0x52, 0x9a, 0x2b, 0x15, 0x2d, 0x15, 0x4c, 0x75, 0xed, 0xe4, 0xff, 0xfc, 0x1e,
	0x3b, 0xb2, 0xde, 0x88, 0x81, 0x0b, 0x2c, 0x24, 0x50, 0x1f, 0x5c, 0x11, 0xf4, 0x1c, 0xc2, 0x82,
	0x7e, 0x04, 0xc2, 0x61, 0x3c, 0x00, 0x2e, 0x1c, 0x4c, 0x25, 0x70, 0xea, 0x45, 0x8e, 0xe4, 0x1e,
	0x15, 0x9e, 0x2f, 0x31, 0xa3, 0x22, 0x7d, 0x08, 0x77, 0x06, 0x0e, 0x01, 0x21, 0xbc, 0x10, 0xec,
	0x98, 0x33, 0xc9, 0x8c, 0x9b, 0x73, 0x51, 0x76, 0x1e, 0x65, 0x67, 0x51, 0xf6, 0x34, 0xca, 0x2e,
	0x46, 0xd9, 0x59, 0xd4, 0xc5, 0x73, 0x21, 0x0b, 0x99, 0xca, 0x71, 0xd2, 0x51, 0x16, 0x59, 0x1b,
	0xea, 0xfa, 0x56, 0x33, 0x2b, 0x62, 0xbc, 0x47, 0xfa, 0x46, 0x87, 0x33, 0x52, 0x41, 0x55, 0x74,
	0xb9, 0xbc, 0xff, 0xfc, 0x38, 0xb1, 0xb4, 0xaf, 0x89, 0x75, 0x10, 0x62, 0xd9, 0xed, 0xb7, 0x6d,
	0x9f, 0x11, 0xa7, 0x00, 0x68, 0x51, 0x28, 0xfe, 0x3d, 0xac, 0xdf, 0x77, 0x84, 0xdf, 0x05, 0xe2,
	0x39, 0x72, 0x10, 0x83, 0x70, 0xda, 0x9e, 0x00, 0x7b, 0xcf, 0xf7, 0xf7, 0x82, 0x80, 0x83, 0x10,
	0x93, 0xc4, 0xba, 0xf2, 0xc4, 0x8b, 0x70, 0xb0, 0x5b, 0xe3, 0xf0, 0xb8, 0x8f, 0x39, 0x04, 0x2f,
	0xa6, 0x83, 0x6a, 0x07, 0x43, 0x14, 0x54, 0xef, 0x72, 0x46, 0xaa, 0x04, 0x0b, 0x81, 0x69, 0x58,
	0x7b, 0xa8, 0x28, 0xc6, 0x6b, 0xa4, 0x97, 0xd2, 0x81, 0x8b, 0xdd, 0xa0, 0xf2, 0x9f, 0x72, 0xf1,
	0xdc, 0x75, 0x63, 0x2d, 0x97, 0xdd, 0xa8, 0x4f, 0x12, 0xcb, 0x5e, 0x81, 0xd2, 0xa8, 0xcf, 0x30,
	0x9b, 0x1d, 0x35, 0x61, 0xbc, 0x45, 0x7a, 0x59, 0x6d, 0xb6, 0xf2, 0xfc, 0xaf, 0x3c, 0xe2, 0x2f,
	0x78, 0x9c, 0x25, 0x9e, 0x56, 0x5a, 0xb3, 0x08, 0xda, 0x62, 0xd9, 0x8c, 0xf1, 0x11, 0xe9, 0x67,
	0x89, 0xd7, 0x03, 0xee, 0xb2, 0xa7, 0xd4, 0x6b, 0x47, 0xe0, 0x8a, 0x38, 0xc2, 0xb2, 0xb2, 0xa1,
	0x6c, 0xbd, 0xdc, 0x76, 0xa9, 0x60, 0xf3, 0x99, 0x20, 0x4c, 0xe4, 0x3f, 0x57, 0xd3, 0x2f, 0x32,
	0x83, 0xd4, 0xc1, 0x9f, 0x24, 0xd6, 0xce, 0x12, 0x49, 0x33, 0xad, 0xd5, 0xca, 0x4a, 0x1d, 0xa6,
	0x95, 0x66, 0xa6, 0x6d, 0x32, 0xbf, 0xa6, 0x74, 0x72, 0x81, 0xee, 0xcc, 0x3f, 0xd2, 0x1d, 0xfd,
	0x46, 0x27, 0x7f, 0xd1, 0x7d, 0x40, 0xba, 0x0e, 0xcf, 0x62, 0xcc, 0x41, 0xb8, 0x98, 0x56, 0x36,
	0x15, 0x6a, 0x90, 0xa3, 0x6e, 0xad, 0x77, 0x9c, 0xf7, 0x00, 0x87, 0x5d, 0x39, 0x49, 0xac, 0x6b,
	0x4b, 0xa8, 0x07, 0x59, 0xe1, 0x06, 0x9d, 0x11, 0xcb, 0x30, 0x9d, 0x33, 0x3e, 0x23, 0xfd, 0x02,
	0xe9, 0x4b, 0xb5, 0x65, 0x04, 0xa4, 0xe7, 0xc6, 0x9c, 0xc5, 0xc0, 0x25, 0x06, 0x51, 0xd9, 0x52,
	0xce, 0x37, 0x28, 0x87, 0xd6, 0xd7, 0x83, 0x36, 0x41, 0x7a, 0x0f, 0x7e, 0x86, 0x4e, 0x12, 0xeb,
	0xf6, 0xb2, 0x93, 0xcf, 0x38, 0xa7, 0xdf, 0x9b, 0xe1, 0xcf, 0x93, 0x45, 0xeb, 0xc6, 0x27, 0xa4,
	0x1b, 0xd3, 0x46, 0x0a, 0x3d, 0x94, 0x54, 0x0f, 0x2f, 0xa7, 0x3d, 0xdc, 0x59, 0xaf, 0x87, 0x53,
	0xfe, 0x9d, 0xd5, 0xfc, 0x8b, 0xec, 0xdb, 0x64, 0x7e, 0x6d, 0xb7, 0xf4, 0x6a, 0x68, 0x69, 0xdf,
	0x87, 0x96, 0xb6, 0x4f, 0x8f, 0x47, 0x26, 0x3a, 0x19, 0x99, 0xe8, 0xdb, 0xc8, 0x44, 0xef, 0xc6,
	0xa6, 0x76, 0x32, 0x36, 0xb5, 0x2f, 0x63, 0x53, 0x7b, 0x74, 0xb4, 0xb2, 0xfa, 0x0f, 0xee, 0xfc,
	0xf6, 0xa6, 0xba, 0x99, 0xaf, 0xff, 0x08, 0x00, 0x00, 0xff, 0xff, 0x92, 0x78, 0x31, 0xe6, 0x39,
	0x06, 0x00, 0x00,
}

func (m *Message) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Message) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MutableProperties.Size()
		i -= size
		if _, err := m.MutableProperties.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMessage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.MutableMetaProperties.Size()
		i -= size
		if _, err := m.MutableMetaProperties.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMessage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.ExpiresIn.Size()
		i -= size
		if _, err := m.ExpiresIn.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMessage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.TakerOwnableSplit.Size()
		i -= size
		if _, err := m.TakerOwnableSplit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMessage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.MakerOwnableSplit.Size()
		i -= size
		if _, err := m.MakerOwnableSplit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMessage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.OrderID.Size()
		i -= size
		if _, err := m.OrderID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMessage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.FromID.Size()
		i -= size
		if _, err := m.FromID.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMessage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.From.Size()
		i -= size
		if _, err := m.From.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintMessage(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintMessage(dAtA []byte, offset int, v uint64) int {
	offset -= sovMessage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Message) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.From.Size()
	n += 1 + l + sovMessage(uint64(l))
	l = m.FromID.Size()
	n += 1 + l + sovMessage(uint64(l))
	l = m.OrderID.Size()
	n += 1 + l + sovMessage(uint64(l))
	l = m.MakerOwnableSplit.Size()
	n += 1 + l + sovMessage(uint64(l))
	l = m.TakerOwnableSplit.Size()
	n += 1 + l + sovMessage(uint64(l))
	l = m.ExpiresIn.Size()
	n += 1 + l + sovMessage(uint64(l))
	l = m.MutableMetaProperties.Size()
	n += 1 + l + sovMessage(uint64(l))
	l = m.MutableProperties.Size()
	n += 1 + l + sovMessage(uint64(l))
	return n
}

func sovMessage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMessage(x uint64) (n int) {
	return sovMessage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Message) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Message: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Message: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.From.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FromID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OrderID.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakerOwnableSplit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MakerOwnableSplit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TakerOwnableSplit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TakerOwnableSplit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresIn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ExpiresIn.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MutableMetaProperties", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MutableMetaProperties.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MutableProperties", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MutableProperties.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMessage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMessage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMessage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMessage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMessage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMessage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMessage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMessage = fmt.Errorf("proto: unexpected end of group")
)
