name: Lint

on:
  pull_request:
    branches:
      - master
      - main
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"

permissions:
  contents: read

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
